### ISSUE TITLE
Text on the header logo appears to be cut off on Mobile.

### ISSUE THREAD

**Issue by Elara6331** [Elara6331/lure-web#1]
It seems the text in the SVG on the header logo gets cut off on some devices, especially Mobile ones. I think this might have to do with the fact that those devices don't have the font I used, so this should be relatively easy to fix by converting the text to a path.

Relevant: Arsen6331/lure#42

**Comment by JamiKettunen** [comment]
Can confirm this happened on a desktop Linux system for me with Firefox 108.

**Comment by Elara6331** [comment]
I've converted the text to a path, can you check to see if it's been fixed? It's possible you may have to clear your cache for the changes to take effect.

**Comment by JamiKettunen** [comment]
Looks fine now :)
![image](https://user-images.githubusercontent.com/47358222/209194665-e91df7f4-3790-4f5e-81a3-87db67307f16.png)

**Comment by Elara6331** [comment]
Great, thanks
